name: starter

services:
  app:
    image: ghcr.io/seprog/starter:latest
    build: .
    depends_on:
      - db
    networks:
      - db-net
    ports:
      - 3000:3000
    post_start:
      - command: bunx prisma db push --skip-generate
    environment:
      DATABASE_URL: postgresql://postgres:starter@db:5432
      AUTH_URL: ${AUTH_URL}
      AUTH_SECRET: ${AUTH_SECRET}
      AUTH_DISCORD_ID: ${AUTH_DISCORD_ID}
      AUTH_DISCORD_SECRET: ${AUTH_DISCORD_SECRET}
      AUTH_GOOGLE_ID: ${AUTH_GOOGLE_ID}
      AUTH_GOOGLE_SECRET: ${AUTH_GOOGLE_SECRET}
      AUTH_GITHUB_ID: ${AUTH_GITHUB_ID}
      AUTH_GITHUB_SECRET: ${AUTH_GITHUB_SECRET}
  db:
    image: postgres:latest
    restart: always
    # set shared memory limit when using docker-compose
    shm_size: 1gb
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - db-net
    environment:
      POSTGRES_PASSWORD: starter
  # optional - for db access
  adminer:
    image: adminer:latest
    restart: always
    networks:
      - db-net
    ports:
      - 8080:8080

volumes:
  db-data:

networks:
  db-net:
