name: Setup Cypress

description: Setup Cypress testing environment

runs:
  using: composite
  steps:
    - uses: oven-sh/setup-bun@v2
    - shell: sh
      run: |
        bun install cypress
        bun cypress install

