name: Run Tests

on:
  workflow_call:
  workflow_dispatch:
  push:
  pull_request:

jobs:
  call-build-docker:
    name: Build Docker Container
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build Docker Container
        uses: ./.github/actions/build-docker

  cypress-electron-component:
    name: Cypress Electron Component Tests
    needs: call-build-docker
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up cypress
        uses: ./.github/actions/setup-cypress

      - name: Build Docker Container
        uses: ./.github/actions/build-docker

      - name: Run Cypress Component Tests
        uses: cypress-io/github-action@v6
        with:
          install: false
          component: true

  cypress-electron-e2e:
    name: Cypress Electron E2E Tests
    needs: call-build-docker
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up cypress
        uses: ./.github/actions/setup-cypress

      - name: Build Docker Container
        uses: ./.github/actions/build-docker

      - name: Start Docker Container
        run: |
          docker compose up -d app db
          bun run db:push

      - name: Run Cypress E2E Tests
        uses: cypress-io/github-action@v6
        with:
          install: false
          wait-on: http://localhost:3000

      - name: Stop Docker Container
        run: docker compose down -v

  cypress-chrome-component:
    name: Cypress Chrome Component Tests
    needs: call-build-docker
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up cypress
        uses: ./.github/actions/setup-cypress

      - name: Build Docker Container
        uses: ./.github/actions/build-docker

      - name: Run Cypress Component Tests
        uses: cypress-io/github-action@v6
        with:
          install: false
          component: true
          browser: chrome

  cypress-chrome-e2e:
    name: Cypress Chrome E2E Tests
    needs: call-build-docker
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up cypress
        uses: ./.github/actions/setup-cypress

      - name: Build Docker Container
        uses: ./.github/actions/build-docker

      - name: Start Docker Container
        run: |
          docker compose up -d app db
          bun run db:push

      - name: Run Cypress E2E Tests
        uses: cypress-io/github-action@v6
        with:
          install: false
          wait-on: http://localhost:3000
          browser: chrome

      - name: Stop Docker Container
        run: docker compose down -v


  cypress-firefox-component:
    name: Cypress Firefox Component Tests
    needs: call-build-docker
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up cypress
        uses: ./.github/actions/setup-cypress

      - name: Build Docker Container
        uses: ./.github/actions/build-docker

      - name: Run Cypress Component Tests
        uses: cypress-io/github-action@v6
        with:
          install: false
          component: true
          browser: firefox

  cypress-firefox-e2e:
    name: Cypress Firefox E2E Tests
    needs: call-build-docker
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up cypress
        uses: ./.github/actions/setup-cypress

      - name: Build Docker Container
        uses: ./.github/actions/build-docker

      - name: Start Docker Container
        run: |
          docker compose up -d app db
          bun run db:push

      - name: Run Cypress E2E Tests
        uses: cypress-io/github-action@v6
        with:
          install: false
          wait-on: http://localhost:3000
          browser: firefox

      - name: Stop Docker Container
        run: docker compose down -v


  cypress-edge-component:
    name: Cypress Edge Component Tests
    needs: call-build-docker
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up cypress
        uses: ./.github/actions/setup-cypress

      - name: Build Docker Container
        uses: ./.github/actions/build-docker

      - name: Run Cypress Component Tests
        uses: cypress-io/github-action@v6
        with:
          install: false
          component: true
          browser: edge

  cypress-edge-e2e:
    name: Cypress Edge E2E Tests
    needs: call-build-docker
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up cypress
        uses: ./.github/actions/setup-cypress

      - name: Build Docker Container
        uses: ./.github/actions/build-docker

      - name: Start Docker Container
        run: |
          docker compose up -d app db
          bun run db:push

      - name: Run Cypress E2E Tests
        uses: cypress-io/github-action@v6
        with:
          install: false
          wait-on: http://localhost:3000
          browser: edge

      - name: Stop Docker Container
        run: docker compose down -v
