name: Run Tests

on:
  workflow_call:
  workflow_dispatch:
  push:
  pull_request:

jobs:
  install:
    name: Install
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up bun
        uses: oven-sh/setup-bun@v2

      - name: Cache node modules
        uses: actions/cache@v4
        with:
          path: ~/.bun
          key: ${{ runner.os }}-node-${{ hashFiles('**/bun.lock') }}

      - name: Cache Cypress binary
        uses: actions/cache@v4
        with:
          path: ~/.cache/Cypress
          key: cypress-${{ runner.os }}-cypress-${{ hashFiles('**/bun.lock') }}

      - name: Cypress install
        run: |
          bun install cypress
          bun cypress install

      - name: Save node module artifacts
        uses: actions/upload-artifact@v4
        with:
          name: node_modules
          if-no-files-found: error
          path: node_modules
      - name: Save cypress binary artifacts
        uses: actions/upload-artifact@v4
        with:
          name: cypress
          if-no-files-found: error
          path: ~/.cache/Cypress

  cypress_component:
    name: Cypress Component
    needs: install
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Load node module artifacts
        uses: actions/download-artifact@v4
        with:
          name: node_modules
          path: node_modules
      - name: Load cypress binary artifacts
        uses: actions/download-artifact@v4
        with:
          name: cypress
          path: ~/.cache/Cypress

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build
        uses: docker/build-push-action@v6
        with:
          load: true
          push: false
          tags: ghcr.io/${{ github.repository }}:latest

      - name: Run Cypress Component Tests
        uses: cypress-io/github-action@v6
        with:
          install: false
          component: true

  cypress_e2e:
    name: Cypress E2E
    needs: install
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Load node module artifacts
        uses: actions/download-artifact@v4
        with:
          name: node_modules
          path: node_modules
      - name: Load cypress binary artifacts
        uses: actions/download-artifact@v4
        with:
          name: cypress
          path: ~/.cache/Cypress

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build
        uses: docker/build-push-action@v6
        with:
          load: true
          push: false
          tags: ghcr.io/${{ github.repository }}:latest

      - name: Run Cypress E2E Tests
        uses: cypress-io/github-action@v6
        with:
          install: false
