name: Run Tests

on:
  workflow_call:
  workflow_dispatch:
  push:
  pull_request:

jobs:
  call-build:
    name: Build
    uses: ./.github/workflows/build.yml

  cypress-electron:
    name: Cypress Electron
    needs: call-build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up cypress
        uses: ./.github/actions/setup-cypress

      - name: Build Docker Container
        uses: ./.github/actions/build-docker

      - name: Start Docker Container
        run: |
          docker compose up -d app

      - name: Run Tests
        uses: cypress-io/github-action@v6
        with:
          install: false
          wait-on: http://localhost:3000

      - name: Stop Docker Container
        run: docker compose down -v

  cypress-chrome:
    name: Cypress Chrome
    needs: call-build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up cypress
        uses: ./.github/actions/setup-cypress

      - name: Build Docker Container
        uses: ./.github/actions/build-docker

      - name: Start Docker Container
        run: |
          docker compose up -d app

      - name: Run Tests
        uses: cypress-io/github-action@v6
        with:
          install: false
          wait-on: http://localhost:3000
          browser: chrome

      - name: Stop Docker Container
        run: docker compose down -v

  cypress-firefox:
    name: Cypress Firefox
    needs: call-build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up cypress
        uses: ./.github/actions/setup-cypress

      - name: Build Docker Container
        uses: ./.github/actions/build-docker

      - name: Start Docker Container
        run: |
          docker compose up -d app

      - name: Run Tests
        uses: cypress-io/github-action@v6
        with:
          install: false
          wait-on: http://localhost:3000
          browser: firefox

      - name: Stop Docker Container
        run: docker compose down -v

  cypress-edge:
    name: Cypress Edge
    needs: call-build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up cypress
        uses: ./.github/actions/setup-cypress

      - name: Build Docker Container
        uses: ./.github/actions/build-docker

      - name: Start Docker Container
        run: |
          docker compose up -d app

      - name: Run Tests
        uses: cypress-io/github-action@v6
        with:
          install: false
          wait-on: http://localhost:3000
          browser: edge

      - name: Stop Docker Container
        run: docker compose down -v
