name: Run Tests

on:
  workflow_call:
  workflow_dispatch:
  push:
  pull_request:

jobs:
  call-build-docker:
    name: Build Docker Container
    runs-on: ubuntu-latest
    steps:
      - name: Build Docker Container
        uses: ./.github/actions/build-docker.yml

  cypress-component:
    name: Cypress Component Tests
    needs: call-build-docker
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up bun
        uses: oven-sh/setup-bun@v2

      - name: Set up cypress
        run: |
          bun install cypress
          bun cypress install

      - name: Build Docker Container
        uses: ./.github/actions/build-docker

      - name: Run Cypress Component Tests
        uses: cypress-io/github-action@v6
        with:
          install: false
          component: true

  cypress-e2e:
    name: Cypress E2E Tests
    needs: call-build-docker
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up bun
        uses: oven-sh/setup-bun@v2

      - name: Set up cypress
        run: |
          bun install cypress
          bun cypress install

      - name: Build Docker Container
        uses: ./.github/actions/build-docker

      - name: Start Docker Container
        run: |
          docker compose up -d app db
          bun run db:push

      - name: Run Cypress E2E Tests
        uses: cypress-io/github-action@v6
        with:
          install: false

      - name: Stop Docker Container
        run: docker compose down -v
