name: Run Tests

on:
  workflow_call:
  workflow_dispatch:
  push:
  pull_request:

jobs:
  build:
    name: Build Container
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build App
        uses: docker/build-push-action@v6
        with:
          load: true
          push: false
          tags: ghcr.io/${{ github.repository }}:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max

  cypress:
    name: Cypress
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up bun
        uses: oven-sh/setup-bun@v2

      - name: Set up cypress
        run: |
          bun install cypress
          bun cypress install

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build App
        uses: docker/build-push-action@v6
        with:
          load: true
          push: false
          tags: ghcr.io/${{ github.repository }}:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Start Container
        run: |
          docker compose up -d app db
          bun run db:push

      - name: Run Cypress E2E Tests
        uses: cypress-io/github-action@v6
        with:
          install: false

      - name: Stop Container
        run: docker compose down -v

      - name: Run Cypress Component Tests
        uses: cypress-io/github-action@v6
        with:
          install: false
          component: true
