name: Run Tests

on:
  workflow_call:
  workflow_dispatch:
  push:
  pull_request:

jobs:
  cypress_component:
    name: Cypress Component
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up bun
        uses: oven-sh/setup-bun@v2

      - name: Set up Cypress
        run: |
          bun install cypress
          bun cypress install

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build
        uses: docker/build-push-action@v6
        with:
          load: true
          push: false
          tags: ghcr.io/${{ github.repository }}:latest

      - name: Run Cypress Component Tests
        uses: cypress-io/github-action@v6
        with:
          install: false
          component: true

  cypress_e2e:
    name: Cypress E2E
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up bun
        uses: oven-sh/setup-bun@v2

      - name: Set up Cypress
        run: |
          bun install cypress
          bun cypress install

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build
        uses: docker/build-push-action@v6
        with:
          load: true
          push: false
          tags: ghcr.io/${{ github.repository }}:latest

      - name: Run Cypress E2E Tests
        uses: cypress-io/github-action@v6
        with:
          install: false
