name: Run Tests

on:
  workflow_call:
  workflow_dispatch:
  push:
  pull_request:

jobs:
  setup:
    name: Setup
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up bun
        uses: oven-sh/setup-bun@v2

      - name: Set up Cypress
        run: |
          bun install cypress
          bun cypress install

      - name: Cache save cypress
        uses: actions/cache/save@v4
        with:
          path: |
            node_modules
            ~/.bun
            ~/.cache/Cypress
          key: cypress-${{ hashFiles('**/bun.lock') }}

#      - name: Set up QEMU
#        uses: docker/setup-qemu-action@v3
#
#      - name: Set up Docker Buildx
#        uses: docker/setup-buildx-action@v3
#
#      - name: Build App
#        uses: docker/build-push-action@v6
#        with:
#          load: true
#          push: false
#          tags: ghcr.io/${{ github.repository }}:latest

  cypress_component:
    name: Cypress Component
    needs: setup
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Cache restore cypress
        uses: actions/cache/restore@v4
        with:
          path: |
            node_modules
            ~/.bun
            ~/.cache/Cypress
          key: cypress-${{ hashFiles('**/bun.lock') }}

      - name: Set up bun
        uses: oven-sh/setup-bun@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build App
        uses: docker/build-push-action@v6
        with:
          load: true
          push: false
          tags: ghcr.io/${{ github.repository }}:latest

      - name: Run Cypress Component Tests
        uses: cypress-io/github-action@v6
        with:
          install: false
          component: true

  cypress_e2e:
    name: Cypress E2E
    needs: setup
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Cache restore cypress
        uses: actions/cache/restore@v4
        with:
          path: |
            node_modules
            ~/.bun
            ~/.cache/Cypress
          key: cypress-${{ hashFiles('**/bun.lock') }}

      - name: Set up bun
        uses: oven-sh/setup-bun@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build App
        uses: docker/build-push-action@v6
        with:
          load: true
          push: false
          tags: ghcr.io/${{ github.repository }}:latest

      - name: Start App and DB
        run: |
          docker compose up -d app db
          bun run db:push

      - name: Run Cypress E2E Tests
        uses: cypress-io/github-action@v6
        with:
          install: false
