name: Run Tests

on:
  workflow_call:
  workflow_dispatch:
  push:
  pull_request:

jobs:
  cypress:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up bun
        uses: oven-sh/setup-bun@v2
      - name: Install Dependencies
        run: bun install

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build
        uses: docker/build-push-action@v6
        with:
          load: true
          push: false
          tags: ghcr.io/${{ github.repository }}:latest

      - name: Start Container
        run: docker compose up -d

      - name: Run Cypress Component Tests
        run: bun run cypress:component:headless
      - name: Run Cypress E2E Tests
        run: bun run cypress:e2e:headless

      - name: Run Component Testing
        uses: cypress-io/github-action@v6
        with:
          install: false
          component: true

      - name: Run E2E Testing
        uses: cypress-io/github-action@v6
        with:
          install: false

      - name: Stop Container
        run: docker compose down
